#include "stdinclude.h"
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <memory.h>

typedef unsigned char uint8_t;
typedef unsigned short uint16_t;
typedef unsigned int uint32_t;

struct bmp_fhdr {
	uint32_t bf_size;
	uint16_t bf_reserved1;
	uint16_t bf_reserved2;
	uint32_t bf_offset;
};

struct bmp_ihdr {
	uint32_t bi_hlen;
	uint32_t bi_width;
	uint32_t bi_height;
	uint16_t bi_planes;
	uint16_t bi_bitcnt;
	uint32_t bi_compression;
	uint32_t bi_size;
	uint32_t bi_xppm;
	uint32_t bi_yppm;
	uint32_t bi_clrused;
	uint32_t bi_clrimportant;
};

#define BM_MAGIC 0x4D42
#define BI_RGB 0x00000000

struct bmp_header {
	uint16_t bm_magic;
	struct bmp_fhdr bm_fhdr;
	struct bmp_ihdr bm_ihdr;
} __attribute__((packed));

struct rgb {
	uint8_t r, g, b;
} __attribute__((packed));


size_t write_bmp24_hdr(FILE *fout, int width, int height)
{
	uint32_t bisize = width * height * 3;

	struct bmp_header bmp = {
		.bm_magic = BM_MAGIC,
		.bm_fhdr = {
			.bf_size = sizeof(struct bmp_header) + bisize,
			.bf_reserved1 = 0,
			.bf_reserved2 = 0,
			.bf_offset = sizeof(struct bmp_header),
		},

		.bm_ihdr = {
			.bi_hlen = sizeof(struct bmp_ihdr),
			.bi_width = width,
			.bi_height = -height,
			.bi_planes = 1,
			.bi_bitcnt = 24,
			.bi_compression = BI_RGB,
			.bi_size = bisize,
			.bi_xppm = 1024,
			.bi_yppm = 1024,
			.bi_clrused = 0,
			.bi_clrimportant = 0,
		},
	};

	if (1 != fwrite(&bmp, sizeof(bmp), 1, fout))
		return 0;

	return 1;
}

size_t read_bmp24_hdr(FILE *fin, int *restrict p_width,
		int *restrict p_height)
{
	struct bmp_header bmp;
	if (1 != fread(&bmp, offsetof(struct bmp_header, bm_ihdr)
				+ offsetof(struct bmp_ihdr, bi_width),
				1, fin)) return 0;

	if (bmp.bm_ihdr.bi_hlen > sizeof(struct bmp_ihdr))
		return 0;

	if (bmp.bm_ihdr.bi_hlen < 4)
		return 0;

	if (1 != fread((char *) &bmp
				+ offsetof(struct bmp_header, bm_ihdr)
				+ offsetof(struct bmp_ihdr, bi_width),
				+ bmp.bm_ihdr.bi_hlen - 4,
				1, fin)) return 0;

	if (bmp.bm_ihdr.bi_compression != BI_RGB)
		return 0;

	if (bmp.bm_ihdr.bi_planes != 1)
		return 0;

	if (bmp.bm_ihdr.bi_bitcnt != 24)
		return 0;

	if (bmp.bm_ihdr.bi_clrused != 0)
		return 0;

	if ((signed) bmp.bm_ihdr.bi_height > 0)
		return 0;

	*p_height = -bmp.bm_ihdr.bi_height;
	*p_width = bmp.bm_ihdr.bi_width;

	return bmp.bm_ihdr.bi_size;
}

#define P6_MAGIC 0x3650

size_t read_ppm6_hdr(FILE *fin, int *restrict p_width,
		int *restrict p_height)
{
	int magic = 0;

	if (!fgets((char *) &magic, 3, fin))
		return 0;

	if (magic != P6_MAGIC)
		return 0;
	while ('\n' != getc(fin));

	if (!fscanf(fin, "%d %d", p_width, p_height))
		return 0;

	int maxval = 0;
	if (!fscanf(fin, "%d", &maxval) || maxval != 255)
		return 0;

	while ('\n' != getc(fin));

	return *p_width * *p_height * 3;
}

size_t write_ppm6_hdr(FILE *fout, int width, int height)
{
	fprintf(fout, "P6# Generated by write_ppm6_hdr\n");
	fprintf(fout, "%d %d\n", width, height);
	fprintf(fout, "255\n");
	return 1;
}

void failed(int status, const char *errfuname)
{
	if (status == -1)
		fprintf(stderr, "error occurred in output : ");
	else if (status == -2)
		fprintf(stderr, "error occurred on input : ");
	else if (status == 0)
		exit(127);

	if (!errfuname)
		fprintf(stderr, "failed\n");
	else
		perror(errfuname);

	exit(status);
}

int main(int argc, char *argv[])
{
	if (argc < 3) {
usage:		fprintf(stderr, "usage: %s <source format> <destinatination format>\n", argv[0]);
		fprintf(stderr, "\tsupported <source format>\t: bmp24 ppm6\n");
		fprintf(stderr, "\tsupported <destination format>\t: bmp24 ppm6\n");
		failed(0, NULL);
	}

	size_t size = 0;
	int width, height;

	if (!strcmp(argv[1], "bmp24"))
		size = read_bmp24_hdr(stdin, &width, &height);
	else if (!strcmp(argv[1], "ppm6"))
		size = read_ppm6_hdr(stdin, &width, &height);
	else
		goto usage;

	if (!size)
		failed(-2, NULL);


	int res = 0;
	if (!strcmp(argv[2], "bmp24"))
		res = write_bmp24_hdr(stdout, width, height);
	else if (!strcmp(argv[2], "ppm6"))
		res = write_ppm6_hdr(stdout, width, height);
	else
		goto usage;

	if (!res)
		failed(-1, NULL);

	for (int i = 0; i < size; i += 3) {
		char rgb[3];
		if (1 != fread(&rgb, 3, 1, stdin))
			failed(-2, "fread");
		/*rgb[0] ^= rgb[2];
		rgb[2] ^= rgb[0];*/
		char tmp = rgb[0];
		rgb[0] = rgb[2];
		rgb[2] = tmp;
		if (1 != fwrite(&rgb, 3, 1, stdout)) {
			failed(-1, "fwrite");
		}
	};

	return 0;
}
